-- Table: public.qrtz_job_history

CREATE TABLE IF NOT EXISTS public.qrtz_job_history
(
    id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    sched_name text COLLATE pg_catalog."default" NOT NULL,
    instance_name text COLLATE pg_catalog."default" NOT NULL,
    job_name text COLLATE pg_catalog."default" NOT NULL,
    job_group text COLLATE pg_catalog."default" NOT NULL,
	package_name text COLLATE pg_catalog."default",
    trigger_name text COLLATE pg_catalog."default" NOT NULL,
    trigger_group text COLLATE pg_catalog."default" NOT NULL,
    fired_time bigint NOT NULL,
    sched_time bigint NOT NULL,
    last_signal_time bigint NOT NULL,
    run_time bigint,
    has_error boolean NOT NULL,
    error_message text COLLATE pg_catalog."default",
	error_details text COLLATE pg_catalog."default",
    vetoed boolean NOT NULL,
    completed boolean NOT NULL,
    CONSTRAINT qrtz_job_history_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.qrtz_job_history
    OWNER to quartz;

GRANT ALL ON TABLE public.qrtz_job_history TO quartz;


-- Table: public.qrtz_job_run_log

CREATE TABLE IF NOT EXISTS public.qrtz_job_run_log
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    job_run_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default",
    is_error boolean NOT NULL,
    create_time bigint NOT NULL,
    CONSTRAINT qrtz_job_run_log_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.qrtz_job_run_log
    OWNER to quartz;

GRANT ALL ON TABLE public.qrtz_job_run_log TO quartz;
-- Index: IX_qrtz_job_run_log_job_run_id

CREATE INDEX IF NOT EXISTS "IX_qrtz_job_run_log_job_run_id"
    ON public.qrtz_job_run_log USING btree
    (job_run_id COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;



-- Table: public.qrtz_job_run_email

CREATE TABLE IF NOT EXISTS public.qrtz_job_run_email
(
    id uuid NOT NULL,
    job_run_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    subject character varying(256) COLLATE pg_catalog."default" NOT NULL,
    body text COLLATE pg_catalog."default" NOT NULL,
    message_to text COLLATE pg_catalog."default" NOT NULL,
    message_cc text COLLATE pg_catalog."default" NOT NULL,
    message_bcc text COLLATE pg_catalog."default" NOT NULL,
    is_sent boolean NOT NULL,
    create_time bigint NOT NULL,
    CONSTRAINT qrtz_job_run_email_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.qrtz_job_run_email
    OWNER to quartz;

GRANT ALL ON TABLE public.qrtz_job_run_email TO quartz;
-- Index: IX_qrtz_job_run_email_job_run_id

CREATE INDEX IF NOT EXISTS "IX_qrtz_job_run_email_job_run_id"
    ON public.qrtz_job_run_email USING btree
    (job_run_id COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;



-- Table: public.qrtz_job_run_attachment

CREATE TABLE IF NOT EXISTS public.qrtz_job_run_attachment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    job_run_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    email_id uuid NULL,
    name character varying(256) COLLATE pg_catalog."default" NOT NULL,
    content_type character varying(128) COLLATE pg_catalog."default" NOT NULL,
    content bytea NOT NULL,
    create_time bigint NOT NULL,
    CONSTRAINT qrtz_job_run_attachment_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.qrtz_job_run_attachment
    OWNER to quartz;

GRANT ALL ON TABLE public.qrtz_job_run_attachment TO quartz;
-- Index: IX_qrtz_job_run_attachment_job_run_id

CREATE INDEX IF NOT EXISTS "IX_qrtz_job_run_attachment_job_run_id"
    ON public.qrtz_job_run_attachment USING btree
    (job_run_id COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;